name: Build and Test

on:
  pull_request:
  push:
    branches: [main]

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Mount bazel caches
        uses: actions/cache@v3.0.11
        with:
          path: |
            ~/.cache
          key: v3-build-cache
          restore-keys: v3-build-cache
      - name: Run Bazel
        run: bazel test //...
